sudo: required
services:
  - docker

before_install:
  - docker build -t arthurwei/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run arthurwei/react-test npm run test -- --coverage

after_success:
  - docker build -t arthurwei/multi-client ./client
  - docker build -t arthurwei/multi-nginx ./nginx
  - docker build -t arthurwei/multi-server ./server
  - docker build -t arthurwei/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push arthurwei/multi-client
  - docker push arthurwei/multi-nginx
  - docker push arthurwei/multi-server
  - docker push arthurwei/multi-worker

deploy:
  provider: dlasticbeanstalk
  region: us-west-2
  app: multi-docker
  env:
  bucker_name:
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

